// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: calculator.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DivideRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dividend      int64                  `protobuf:"varint,1,opt,name=dividend,proto3" json:"dividend,omitempty"`
	Divisor       int64                  `protobuf:"varint,2,opt,name=divisor,proto3" json:"divisor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DivideRequest) Reset() {
	*x = DivideRequest{}
	mi := &file_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DivideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivideRequest) ProtoMessage() {}

func (x *DivideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivideRequest.ProtoReflect.Descriptor instead.
func (*DivideRequest) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *DivideRequest) GetDividend() int64 {
	if x != nil {
		return x.Dividend
	}
	return 0
}

func (x *DivideRequest) GetDivisor() int64 {
	if x != nil {
		return x.Divisor
	}
	return 0
}

type DivideReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quotient      int64                  `protobuf:"varint,1,opt,name=quotient,proto3" json:"quotient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DivideReply) Reset() {
	*x = DivideReply{}
	mi := &file_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DivideReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivideReply) ProtoMessage() {}

func (x *DivideReply) ProtoReflect() protoreflect.Message {
	mi := &file_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivideReply.ProtoReflect.Descriptor instead.
func (*DivideReply) Descriptor() ([]byte, []int) {
	return file_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *DivideReply) GetQuotient() int64 {
	if x != nil {
		return x.Quotient
	}
	return 0
}

var File_calculator_proto protoreflect.FileDescriptor

const file_calculator_proto_rawDesc = "" +
	"\n" +
	"\x10calculator.proto\x12\n" +
	"calculator\"E\n" +
	"\rDivideRequest\x12\x1a\n" +
	"\bdividend\x18\x01 \x01(\x03R\bdividend\x12\x18\n" +
	"\adivisor\x18\x02 \x01(\x03R\adivisor\")\n" +
	"\vDivideReply\x12\x1a\n" +
	"\bquotient\x18\x01 \x01(\x03R\bquotient2J\n" +
	"\n" +
	"Calculator\x12<\n" +
	"\x06Divide\x12\x19.calculator.DivideRequest\x1a\x17.calculator.DivideReplyB\tZ\a./;mainb\x06proto3"

var (
	file_calculator_proto_rawDescOnce sync.Once
	file_calculator_proto_rawDescData []byte
)

func file_calculator_proto_rawDescGZIP() []byte {
	file_calculator_proto_rawDescOnce.Do(func() {
		file_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calculator_proto_rawDesc), len(file_calculator_proto_rawDesc)))
	})
	return file_calculator_proto_rawDescData
}

var file_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_calculator_proto_goTypes = []any{
	(*DivideRequest)(nil), // 0: calculator.DivideRequest
	(*DivideReply)(nil),   // 1: calculator.DivideReply
}
var file_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.Calculator.Divide:input_type -> calculator.DivideRequest
	1, // 1: calculator.Calculator.Divide:output_type -> calculator.DivideReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculator_proto_init() }
func file_calculator_proto_init() {
	if File_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculator_proto_rawDesc), len(file_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_proto_goTypes,
		DependencyIndexes: file_calculator_proto_depIdxs,
		MessageInfos:      file_calculator_proto_msgTypes,
	}.Build()
	File_calculator_proto = out.File
	file_calculator_proto_goTypes = nil
	file_calculator_proto_depIdxs = nil
}
